r"""Version control and provenance: one repository per paper.

Implements §11 of the pipeline standard.  The history *is* the record of how a
result was reached, so every commit that carries a number also carries the seed,
config hash and tracking run id that produced it.

Token handling — the part that goes wrong
-----------------------------------------
A fine-grained PAT is **never** accepted through this API as a plain argument
from a chat, never written into a remote URL, and never committed.
:func:`load_pat` reads it from Colab Secrets (or the environment) at runtime,
and :func:`push` passes it per-invocation through a credential helper:

.. code-block:: bash

    git -c credential.helper='!f(){ echo username=x-access-token; \
        echo password=$GITHUB_PAT; };f' push origin main

``git remote set-url https://<token>@github.com/...`` is the tempting
one-liner and it persists the secret in ``.git/config``, which then leaks with
any copy of the repo.  :func:`assert_no_token_in_config` fails the run if a
token-shaped string ever appears there.

Scope the PAT to the single paper repository, grant **Contents: read/write**
and nothing else, and set an expiry of 90 days or less.

Commit policy
-------------
* ``commit_on_new_best`` — fires only when the validation metric improves on the
  previous best.  Not every epoch, not every checkpoint.
* ``commit_artifacts`` — one commit at end of run carrying ``.tex`` tables,
  vector plots and the profiling summary, which are produced after training
  stops and would otherwise never land.

What is tracked: code, configs, generated tables and plots, the provenance
record and the intervention log.  ``best_model.pt`` is the only weight file, via
Git LFS; intermediate checkpoints stay on Drive and are referenced by path.
"""

from __future__ import annotations

import logging
import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence

__all__ = ["GitRepo", "load_pat", "PAT_ENV", "GITIGNORE", "GITATTRIBUTES",
           "provenance_message"]

log = logging.getLogger("amdt.repo")

PAT_ENV = "GITHUB_PAT"

#: Token shapes GitHub currently issues. Used only to *detect* accidental leaks.
_TOKEN_RE = re.compile(r"gh[pousr]_[A-Za-z0-9]{16,}|github_pat_[A-Za-z0-9_]{20,}")

GITIGNORE = """\
# Credentials. Listed FIRST and committed before anything else -- a key that
# has ever been committed must be rotated, because history retains it.
kaggle.json
.kaggle/
.env
*.pem
*.key

# Run artifacts -- regenerated by run_experiments.py, never committed
outputs/
wandb/
optuna.db
runs_registry.json

# Data -- downloaded into a cache outside the repo, never committed
data/
*.pgm
*.zip

# Weights: only best_model.pt is tracked (via LFS); everything else stays on Drive.
*.pt
!best_model.pt
*.ckpt

__pycache__/
*.pyc
.venv/
.pytest_cache/
.DS_Store
"""

GITATTRIBUTES = "best_model.pt filter=lfs diff=lfs merge=lfs -text\n"


# --------------------------------------------------------------------------- #
def load_pat() -> Optional[str]:
    """Read the PAT from Colab Secrets, else the environment. Never from chat."""
    try:
        from google.colab import userdata  # type: ignore
        token = userdata.get(PAT_ENV)
        if token:
            os.environ[PAT_ENV] = token
            return token
    except Exception:
        pass
    return os.environ.get(PAT_ENV)


def provenance_message(subject: str, seed: int, config_hash: str,
                       run_id: Optional[str] = None, trigger: str = "manual",
                       agent_revision: Optional[str] = None,
                       extra: Optional[Dict[str, object]] = None) -> str:
    """Commit message carrying enough provenance to trace any reported number."""
    lines = [subject, ""]
    body = {"seed": seed, "config_hash": config_hash}
    if run_id:
        body["wandb_run"] = run_id
    body["trigger"] = trigger
    if agent_revision:
        body["agent_revision"] = agent_revision
    body.update(extra or {})
    lines += [f"{k}: {v}" for k, v in body.items()]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
@dataclass
class GitRepo:
    root: Path
    remote: Optional[str] = None          # https://github.com/<owner>/<repo>.git
    branch: str = "main"
    author_name: str = "amdt-pipeline"
    author_email: str = "amdt-pipeline@localhost"

    def __post_init__(self) -> None:
        self.root = Path(self.root)

    # -- plumbing --------------------------------------------------------
    def _run(self, *args: str, check: bool = True, env: Optional[Dict[str, str]] = None
             ) -> subprocess.CompletedProcess:
        return subprocess.run(["git", *args], cwd=str(self.root), text=True,
                              capture_output=True, check=check,
                              env={**os.environ, **(env or {})})

    @property
    def initialised(self) -> bool:
        return (self.root / ".git").exists()

    def init(self, lfs: bool = True) -> None:
        """Create the repo, write the ignore/LFS policy, make the first commit."""
        if not self.initialised:
            self._run("init", "-b", self.branch)
        self._run("config", "user.name", self.author_name)
        self._run("config", "user.email", self.author_email)
        (self.root / ".gitignore").write_text(GITIGNORE)
        if lfs:
            (self.root / ".gitattributes").write_text(GITATTRIBUTES)
            r = self._run("lfs", "install", "--local", check=False)
            if r.returncode != 0:
                log.warning("git-lfs unavailable; best_model.pt will not be tracked "
                            "by LFS. Install git-lfs before committing weights.")
        if self.remote:
            existing = self._run("remote", check=False).stdout.split()
            if "origin" in existing:
                self._run("remote", "set-url", "origin", self.remote)
            else:
                self._run("remote", "add", "origin", self.remote)
        # Commit the policy immediately. An uncommitted .gitignore is worse than
        # none: the next `git add` sweeps outputs/, wandb/ and every checkpoint
        # into the index before anyone notices.
        self.commit([".gitignore", ".gitattributes"],
                    "chore: ignore and LFS policy\n\ntrigger: repo_init\n")
        self.assert_no_token_in_config()

    # -- safety ----------------------------------------------------------
    def assert_no_token_in_config(self) -> None:
        """Fail loudly if a token ever lands in ``.git/config``."""
        cfg = self.root / ".git" / "config"
        if cfg.exists() and _TOKEN_RE.search(cfg.read_text()):
            raise RuntimeError(
                f"a GitHub token is embedded in {cfg}. Remove it "
                "(`git remote set-url origin <clean-url>`), revoke the token, and "
                "pass credentials per-invocation instead -- see amdt.utils.repo."
            )

    # -- state -----------------------------------------------------------
    def head(self) -> Optional[str]:
        r = self._run("rev-parse", "HEAD", check=False)
        return r.stdout.strip() or None

    def is_dirty(self) -> bool:
        return bool(self._run("status", "--porcelain", check=False).stdout.strip())

    # -- commits ---------------------------------------------------------
    def commit(self, paths: Sequence[str | Path], message: str,
               allow_empty: bool = False) -> Optional[str]:
        """Stage ``paths`` and commit. Returns the new SHA, or ``None`` if nothing changed."""
        if not self.initialised:
            log.debug("no git repo at %s; skipping commit", self.root)
            return None
        existing = [str(p) for p in paths if (self.root / p).exists()]
        if not existing and not allow_empty:
            return None
        self._run("add", "--", *existing, check=False)
        if not allow_empty and not self._run("diff", "--cached", "--name-only",
                                             check=False).stdout.strip():
            return None
        args = ["commit", "-m", message]
        if allow_empty:
            args.insert(1, "--allow-empty")
        r = self._run(*args, check=False)
        if r.returncode != 0:
            log.warning("git commit failed: %s", (r.stderr or r.stdout).strip())
            return None
        return self.head()

    def commit_on_new_best(self, metric_name: str, value: float, previous: float,
                           epoch: int, seed: int, config_hash: str,
                           run_id: Optional[str] = None,
                           paths: Sequence[str | Path] = ("src", "configs", "best_model.pt"),
                           agent_revision: Optional[str] = None) -> Optional[str]:
        msg = provenance_message(
            f"best: {metric_name} {value:.4f} (prev {previous:.4f}) @ epoch {epoch}",
            seed=seed, config_hash=config_hash, run_id=run_id,
            trigger="new_best_val", agent_revision=agent_revision,
        )
        return self.commit(paths, msg)

    def commit_artifacts(self, run_dir: str | Path, seed: int, config_hash: str,
                         run_id: Optional[str] = None,
                         paper_dir: str = "paper") -> Optional[str]:
        r"""End-of-run commit: tables, vector plots, profiling, intervention log.

        Artifacts are *copied* out of the timestamped, gitignored ``outputs/``
        run directory into a stable tracked path (``paper/tables``,
        ``paper/figures``, ``paper/results``) before committing.  Two reasons:

        * ``outputs/`` is gitignored, so committing from there would need
          ``git add -f`` and would drag along logs and checkpoints;
        * the manuscript should ``\input{paper/tables/tab_quality.tex}`` at a
          path that does not change every run -- otherwise a re-run silently
          leaves the paper pointing at stale numbers.
        """
        import shutil

        run = Path(run_dir)
        if not run.exists():
            log.warning("run directory %s does not exist; nothing to commit", run)
            return None

        dest_root = self.root / paper_dir
        copied: List[Path] = []
        for sub in ("tables", "figures", "results"):
            src = run / sub
            if not src.is_dir():
                continue
            dst = dest_root / sub
            dst.mkdir(parents=True, exist_ok=True)
            for f in sorted(src.iterdir()):
                if f.is_file():
                    shutil.copy2(f, dst / f.name)
            copied.append(dst.relative_to(self.root))

        for fname in ("provenance.json", "resolved_config.yaml", "index.json",
                      "agent_interventions.jsonl"):
            f = run / fname
            if f.is_file():
                dest_root.mkdir(parents=True, exist_ok=True)
                shutil.copy2(f, dest_root / fname)
                copied.append((dest_root / fname).relative_to(self.root))

        if not copied:
            log.warning("no artifacts found under %s; nothing committed", run)
            return None

        msg = provenance_message(
            f"results: {run.name}", seed=seed, config_hash=config_hash,
            run_id=run_id, trigger="end_of_run",
            extra={"run_dir": str(run)},
        )
        return self.commit(copied, msg)

    # -- remote ----------------------------------------------------------
    def push(self, branch: Optional[str] = None, token: Optional[str] = None) -> bool:
        """Push using a per-invocation credential helper. The token is never stored."""
        if not self.remote:
            log.debug("no remote configured; skipping push")
            return False
        token = token or load_pat()
        if not token:
            log.warning("no %s available (Colab Secrets or environment); "
                        "commits stay local. See amdt.utils.repo for PAT setup.", PAT_ENV)
            return False
        self.assert_no_token_in_config()
        helper = ("!f(){ echo username=x-access-token; "
                  f"echo password=${PAT_ENV}; }};f")
        r = self._run("-c", f"credential.helper={helper}",
                      "push", "origin", branch or self.branch,
                      check=False, env={PAT_ENV: token})
        if r.returncode != 0:
            log.warning("git push failed: %s", (r.stderr or r.stdout).strip())
            return False
        return True

    def push_patch_branch(self, patch_path: str | Path, branch: str = "agent/patches",
                          message: str = "agent: proposed patch",
                          token: Optional[str] = None) -> bool:
        """Publish a supervisor patch on its own branch, leaving ``main`` untouched."""
        cur = self._run("rev-parse", "--abbrev-ref", "HEAD", check=False).stdout.strip()
        self._run("checkout", "-B", branch, check=False)
        self.commit([patch_path], message)
        ok = self.push(branch, token)
        if cur:
            self._run("checkout", cur, check=False)
        return ok
